###

GET https://localhost:5002/WeatherForecast

###
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=weatherapi.read&client_id=m2m.client&client_secret=SuperSecretPassword

###

GET https://localhost:5002/WeatherForecast
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFBREExMThFNUQwQTVENTM3RjZCMkUyNURCMTY3M0I0IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjE1NzYwNTQxLCJpYXQiOjE2MTU3NjA1NDEsImV4cCI6MTYxNTc2NDE0MSwiYXVkIjoid2VhdGhlcmFwaSIsInNjb3BlIjpbIndlYXRoZXJhcGkucmVhZCJdLCJjbGllbnRfaWQiOiJtMm0uY2xpZW50IiwianRpIjoiNjYwMEU1RkQ0QUE2QTM1QTc4Q0EwNDI3MkMxMjI2MUIifQ.J65aKgNiw1sxNpTvLuaSc1K6reQDZmhu7JIqwmN3Z806WCoM4Yb_mI_7SnrxqmtJh82l4rcpbN6TvLxyl1_9QP0GfEpUuiPjCpKgvqxY6GMgJasaQISwP8dxH6ZDzFQXFXsceRu7xUxdJiO11DfxDao497skWNn9DBd0AG2q9qLHlWF1sgnKonOi7o0qBYYezowiQ3Fp-sme3HHV5FJKqa5vbiYSG0fbHCrxxGhNmurnLcsnbggW48lHuAnsqIPsEhOd2GV2QR4yuSQBmK9VyebQG4F5gQjslx8OLgqBZoanz3VntH6MmEkLxlruMv8KBYyROtro0j4JpUDkpaIDsQ