###

GET https://localhost:5002/WeatherForecast

###
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=weatherapi.read&client_id=m2m.client&client_secret=SuperSecretPassword

###

GET https://localhost:5002/WeatherForecast
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFBREExMThFNUQwQTVENTM3RjZCMkUyNURCMTY3M0I0IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjE1ODU4OTAzLCJpYXQiOjE2MTU4NTg5MDMsImV4cCI6MTYxNTg2MjUwMywiYXVkIjoid2VhdGhlcmFwaSIsInNjb3BlIjpbIndlYXRoZXJhcGkucmVhZCJdLCJjbGllbnRfaWQiOiJtMm0uY2xpZW50IiwianRpIjoiNDFGQUE1MjU1NTUxQUIwODVBMjg4NkYwRTA4Q0RGQkIifQ.C3KnoVM9NeTgOO1x2MANGjJjOPwjY5tJc7-utUubg5k-EzAdKtqV5PDsf-57_2wrExWIwO5-eYmhzwREzcuO2sY0lhRtc5cric75JuY3cjhNSEmXMACZTm01QHSVyymra2j6gWG1OGHJ6x8T8_0rfucCI_wEuJk_yftOkD5K_PS7jxHmH533dIFRtuFRKdYwh4jnYCagoSpSgfZN9tXmV3tFq9cAV-1z29GS0v_AfTMtrKcARAaR7OZBK9N0U4_HzxI-BpM8XH6c8ydn6LI6O8ZSiKHnLmBBAEfvp7HEfDOQy5r-6w_uBwwL47zXhcLlN9DRwDxdVpiDir5VC7Ks3w